### ISSUE TITLE
[AVM Module Issue]: WAF Alignment - Threat Intelligence for Azure Firewall should by set to Deny mode by default

### ISSUE THREAD

**Issue by JWilkinsonMB** [Azure/terraform-azurerm-avm-ptn-virtualwan#111]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

v0.5.0

### Description

A WAF [recommendation](https://learn.microsoft.com/en-us/azure/well-architected/service-guides/azure-firewall#recommendations-1) for Azure Firewall is to _"Enable [threat intelligence](https://learn.microsoft.com/en-us/azure/firewall/threat-intel) on Azure Firewall in Alert and deny mode."_

Currently this module is defaulting to Alert, not Deny.
https://github.com/Azure/terraform-azurerm-avm-ptn-virtualwan/blob/63740a433741f479ece2471aa0756180f550eebe/variables.tf#L93

Can this be changed so that the module aligns with the AVM principle to follow WAF where possible?

**Comment by jtracey93** [comment]
Thanks @JWilkinsonMB 

However, these should be configured on the Azure Firewall Policy that is associated to the Firewall/s. This is done outside of this module and you associate the firewall policy via the var.firewalls.<mapKey>.firewall_policy_id input.

This is the recommended way to manage the azure firewalls in VWAN as shown here https://learn.microsoft.com/en-us/azure/firewall-manager/quick-secure-virtual-hub-terraform

The line of code you reference above isn't actually passed to a resource to configure and we will remove in an upcoming release of the module to avoid confusion

**Comment by JWilkinsonMB** [comment]
@jtracey93 please can this be reopened. 

I don't disagree that the threat intelligence settings should be defined explicitly on the firewall policy, however as a default for the firewall itself should it not be set to the WAF recommended value?  

Whilst the variable is not used, it probably should be, because the `azurerm_firewall` resource has a parameter for [threat_intel_mode](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#threat_intel_mode-2) which defaults to `Alert` when not set. 

We're not actually using Azure firewall, however not setting this parameter and allowing it to default to Alert is causing IaC code scanning using Checkov to flag it as a vulnerability with the module. 

https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AzureFirewallDenyThreatIntelMode.py

```
Check: CKV_AZURE_216: "Ensure DenyIntelMode is set to Deny for Azure Firewalls"
	FAILED for resource: module.vwan.module.hub.azurerm_firewall.fw
Error: 	File: /.external_modules/github.com/Azure/terraform-azurerm-avm-ptn-virtualwan/63740a433741f479ece2471aa0756180f550eebe/firewall.tf:1-15
	Calling File: /modules/vwan/main.tf:1-35
	Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/azure-policies/azure-networking-policies/bc-azure-216

		1  | resource "azurerm_firewall" "fw" {
		2  |   for_each = var.firewalls
		3  | 
		4  |   location            = azurerm_virtual_hub.virtual_hub[each.value.virtual_hub_key].location
		5  |   name                = each.value.name
		6  |   resource_group_name = azurerm_virtual_hub.virtual_hub[each.value.virtual_hub_key].resource_group_name
		7  |   sku_name            = each.value.sku_name
		8  |   sku_tier            = each.value.sku_tier
		9  |   firewall_policy_id  = each.value.firewall_policy_id
		10 |   tags                = try(each.value.tags, {})
		11 | 
		12 |   virtual_hub {
		13 |     virtual_hub_id = azurerm_virtual_hub.virtual_hub[each.value.virtual_hub_key].id
		14 |   }
		15 | }
```

**Comment by jtracey93** [comment]
Hey @JWilkinsonMB,

Thanks for the reply. We are actually going to remove this variable in the next release as not being used. From what i understand and have read, the only supported way to configure the azure firewall in a VWAN Secured Hub is via the use of a Azure Firewall Policy, and **not** configuring directly on the firewall resource itself, like you can in a hub & spoke model. 

Meaning local policies are not supported on the azure firewall resource in a Secure VWAN Hub deployment model.

However from an ARM perspective the same RP and Resource Type is used to deploy the firewall into both a  Secure VWAN Hub deployment & a traditional hub and spoke vNet model, controlled via the [`sku_name`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#sku_name-1) variable, in TF.

Therefore i actually think this is a false positive on the checkov rule as it shouldn't be checking for this if the [`sku_name`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#sku_name-1) variable is set to `AZFW_Hub`

Sources:

- https://learn.microsoft.com/en-us/azure/firewall-manager/secure-cloud-network
- https://learn.microsoft.com/en-us/azure/firewall-manager/quick-secure-virtual-hub-terraform
- https://learn.microsoft.com/en-us/azure/virtual-wan/howto-firewall
- https://learn.microsoft.com/en-us/azure/firewall-manager/deployment-overview#secured-virtual-hubs

**Comment by JWilkinsonMB** [comment]
Thanks for the explanation. Even though it may have no effect, can `threat_intel_mode = "Deny"` still be set on the firewall resource as a way to clear the false positive, or does this cause other issues?

**Comment by jtracey93** [comment]
No problems 👍 

We'd rather not maintain a variable that is never used in the configuration, it will just cause confusion.

Hope you understand

**Comment by JWilkinsonMB** [comment]
Rather than keeping the variable I was thinking it could just be hardcoded into the resource if it makes no difference. 

I'll do some tests when I have time. If setting the parameter makes no difference to the resource that gets deployed, or if it causes a deployment error then I'll raise it as an issue on the Checkov side. 

If setting `threat_intel_mode = "Deny"` on `azurerm_firewall` actually does change the deployed resource then would you agree it should be set in the module?

**Comment by jtracey93** [comment]
If it does, 100% agree we should set, if an azure firewall policy isnt provided though.

If you can do some testing and let us know and create a PR to update, if required, that'd be amazing!

Thanks
