### ISSUE TITLE
[AVM Module Issue]: vHub Resource Group not being used

### ISSUE THREAD

**Issue by krottiers** [Azure/terraform-azurerm-avm-ptn-virtualwan#42]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### Description

When providing a resource group in the vhub configuration this isn't used. Instead the default Azure vWAN resource group 

Resource deployment references to local.resource_group_name instead of the passed value: 
```
resource "azurerm_virtual_hub" "virtual_hub" {
  for_each = local.virtual_hubs != null && length(local.virtual_hubs) > 0 ? local.virtual_hubs : {}

  location            = each.value.location
  name                = each.value.name
  resource_group_name = local.resource_group_name
  address_prefix      = each.value.address_prefix
  tags                = try(each.value.tags, {})
  virtual_wan_id      = azurerm_virtual_wan.virtual_wan.id
}
```
locals:
```
virtual_hubs = {
    for key, vhub in var.virtual_hubs : key => {
      name           = vhub.name
      location       = vhub.location
      resource_group = try(vhub.resource_group, "")
      address_prefix = vhub.address_prefix
      tags           = try(vhub.tags, {})
    }
  }
```

**Comment by khushal08** [comment]
Fix pushed in v0.4.2.0
