### ISSUE TITLE
[Bug]: Wrong ER local peering_id being used & routing condition failure

### ISSUE THREAD

**Issue by krottiers** [Azure/terraform-azurerm-avm-ptn-virtualwan#44]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### (Optional) Module Version

0.3.0

### Description

2 issues when providing an ER circuit to connect into an ER GW leads to failure of plan:
- Wrong local reference:
`express_route_circuit_peering_id = each.value.er_circuit_peering_id`
- Condition issue when routing is null which is an optional parameter:
`for_each = each.value.routing != null && length(each.value.routing) > 0`

**Comment by khushal08** [comment]
This has been fixed and code changes merged. New release (v0.4.0) created to be published in the Terraform registry.
