### ISSUE TITLE
[Feature]: Missing hub routing preference

### ISSUE THREAD

**Issue by krottiers** [Azure/terraform-azurerm-avm-ptn-virtualwan#55]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Currently hub routing preference is not supported on the per hub config object. The TF resource module supports [this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub#hub_routing_preference).

A needed feature to be able to change the routing configuration on a per hub level.

**Comment by ChrisSidebotham** [comment]
Duplicate of #28
