### ISSUE TITLE
Bug: azurerm_vpn_gateway missing configuration for scale_unit, routing_preference, bgp settings

### ISSUE THREAD

**Issue by OmnipotentOwl** [Azure/terraform-azurerm-avm-ptn-virtualwan#7]
## Summary
When attempting to use the module and configure the scale units or routing preferences for the azurerm_vpn_gateway in the module the configuration is not passed to the resource because the input variables are not mapped to the resource.

## Reproduction
Attempt to deploy the module and configure one of the missing properties using the input variables available.

**Comment by khushal08** [comment]
Hi @OmnipotentOwl 
Are you able to create a PR from your forked repo?

**Comment by jchancellor-ms** [comment]
@khushal08 - Is this still an issue?  Or can we close it?
