### ISSUE TITLE
[AVM Module Issue]: VNET connection propagation cannot be used in network.tf

### ISSUE THREAD

**Issue by davecheung-pwc** [Azure/terraform-azurerm-avm-ptn-virtualwan#74]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

in network.tf, variable routing.propagateed_route_tables

should change propagated_route_tables.value.labels to propagated_route_table.value.labels in order to work

**Comment by jchancellor-ms** [comment]
This has been corrected in PR #90.  Pending final testing, merging, and release.
